### ISSUE TITLE
Plugin isn't setting up custom server settings anymore.

### ISSUE THREAD

**Issue by jipgg** [lopi-py/luau-lsp.nvim#25]
Currently my LSP options seemingly aren't getting initialized correctly anymore since syncing the plugin to the latest commits. In my case imports and strict datamodel types aren't being set to their respective state that i specified; Being import disabled and server diagnostics being non-strict while having both configured to be the opposite. 
In case it could be an error on my part, below is my current config for the plugin that is passed to the mason handlers setup:
```lua
require("luau-lsp").setup({
        platform = {
            type = "roblox",
        },
        plugin = {
            enabled = true,
            port = 3667,
        },
        types = {
            roblox_security_level = "PluginSecurity"
        },
        server = {
            settings = {
                ["luau-lsp"] = {
                    completion = {
                        diagnostics = {
                            strictDatamodelTypes = true,
                        },
                        imports = {
                            suggestServices = true,
                            suggestRequires = false,
                            enabled = true,
                        },
                    },
                },
            },
        },
    })
```

**Comment by lopi-py** [comment]
My settings still are being respected, can you run `:LspInfo` and `:checkhealth luau-lsp` when luau-lsp is attached and send the output?

**Comment by lopi-py** [comment]
1. I've updated the plugin (unrelated changes tbh but who knows), so download the latest version
1. Try visualizing the settings, open a luau file and run `:lua vim.print(require("luau-lsp.util").get_client().settings)` or `:LazyDev lsp`
3. If it shows as expected, try `:LuauLsp restart`
4. If still does not work, try pinning luau-lsp.nvim commits in this specific order: `131d385` `ae76ec9` `3ad89b5`
5. Try loading luau-lsp.nvim at startup and leave the mason handler empty (`function() end`) Actually I think this shouldn't change anything because you seem to already load luau-lsp at startup

I'm using the latest commit right now and the settings are all respected

**Comment by jipgg** [comment]
Pinning to `3ad89b5` resolves the issue.  Looking at the output of `:LspInfo` it seems to be rawdogging the executable on the other versions (image on my previous comment), and only invoking the mason CMD file on the older commit.
<img width="1026" alt="LspInfo-older-commit" src="https://github.com/user-attachments/assets/2a314722-f6d8-4c83-9bb4-deb28f4bacc9">
I do have a separate `luau-lsp.exe`  added to my PATH which seems to be the one that is getting invoked instead of the mason copy thats in nvim-data. Removing said executable from my path breaks functionality entirely and gives an error message on the later commits while silently breaking functionality on the commit that works.
<img width="1280" alt="errMsg-when- removing- bin" src="https://github.com/user-attachments/assets/45de1dd4-05d4-4da7-b65c-0ba62aa55509">
This is however speculation based on a severe lack of knowledge about LSPs, but hopefully this extra information might make it easier for you to diagnose what the problem might be. Regardless, thank you for your help. it's working as expected now.

**Comment by lopi-py** [comment]
Ok, I see the problem: `mason-lspconfig.nvim` will [modify the cmd on Windows](https://github.com/williamboman/mason-lspconfig.nvim/blob/ba9c2f0b93deb48d0a99ae0e8d8dd36f7cc286d6/lua/mason-lspconfig/lspconfig_hook.lua#L80-L83). `mason.nvim` creates a `luau-lsp.CMD` file under the binaries directory. `vim.lsp.start_client` uses `uv.spawn` under the hood, which doesn't execute batch scripts (.CMD files). It wasn't a problem before the commit you are using because I was depending on lspconfig, and mason-lspconfig would "fix" that. I'll add tests for Windows and fix that. Thanks!

**Comment by lopi-py** [comment]
@jipgg Hello, recently I discovered this was related to the fact that you didn't send the capabilities in the server config, I've updated the plugin, so no changes are required on your side, you just need to update the plugin
