### ISSUE TITLE
Unknown global with definitions_file provided

### ISSUE THREAD

**Issue by eriickz** [lopi-py/luau-lsp.nvim#31]
Hello!.

This is my config:
![image](https://github.com/user-attachments/assets/196e381d-bfad-44a8-a1aa-42c52a8a7460)

But I getting unkown global error:
![image](https://github.com/user-attachments/assets/cd752fe0-3555-495b-ba82-c29c4384729c)

Don't mind these dots in these paths, they are just placeholders. I can remove the documentation_files option and the completions still works fine

**Comment by eriickz** [comment]
I removed the `documentation_files` and `definition_files` but the problem persist.

:checkhealth luau-lsp
![image](https://github.com/user-attachments/assets/97ee1d43-8146-43e5-99b1-c97750d6cfa2)

:LspInfo
![image](https://github.com/user-attachments/assets/7ab681c3-41c0-4ee3-909d-5bb045f90665)

:LuauLsp log
`12:53:08[INFO] Starting sourcemap generation for 'default.project.json'`

Also i got this error every time I tried to modify the file:
![image](https://github.com/user-attachments/assets/171914c3-b5eb-4a75-b5de-c4975078a4bd)

Regards!

**Comment by lopi-py** [comment]
The server is working as expected, but you have called `lspconfig.luau_lsp.setup` somewhere so that's creating another server that does not receive any configuration from `luau-lsp.nvim`. As you can see in `:LspInfo`, you have 2 servers spawned. Try to search in your config for `lspconfig` calls.

Check this comment for the error when you try to edit a file: https://github.com/lopi-py/luau-lsp.nvim/issues/30#issuecomment-2307929937

**Comment by eriickz** [comment]
I managed to fix it. 

I'm using LunarVim and the default configuration of Mason that automatically install language servers, so I and included `lua-lsp` to the skipped servers and run `:LvimResetCache` (also I removed the language server that Mason installed before).

I included this in my `config.lua`:
`vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "luau-lsp" })`

Now it worked as expected. Thanks for you support @lopi-py!
